name: Update Bitcoin Price

# Add permissions at the top level
permissions:
  contents: write  # This gives permission to write to the repository

on:
  schedule:
    # Runs at 00:00, 06:00, 12:00, and 18:00 UTC every day
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-price:
    runs-on: ubuntu-latest
    
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run price update script
      run: python fetch_btc_price.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'turnwol7'
        git config --global user.email 'justinb.developer@gmail.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Bitcoin price" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
