name: Update Bitcoin Price

permissions:
  contents: write

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-price:
    runs-on: ubuntu-latest
    
    timeout-minutes: 2
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run price update script
      run: python fetch_btc_price.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'turnwol7'
        git config --global user.email 'justinb.developer@gmail.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Bitcoin price" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
